SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `Books` (
  `id` int(11) NOT NULL,
  `author` varchar(255) COLLATE utf8_polish_ci NOT NULL,
  `title` varchar(255) COLLATE utf8_polish_ci NOT NULL,
  `publication_date` date NOT NULL,
  `description` text COLLATE utf8_polish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

INSERT INTO `Books` (`id`, `author`, `title`, `publication_date`, `description`) VALUES
(1, 'Andrzej Sapkowski', 'Wiedźmin. Tom 1. Ostatnie życzenie', '2014-10-06', 'Andrzej Sapkowski, arcymistrz światowej fantasy, zaprasza do swojego Neverlandu i przedstawia uwielbianą przez czytelników i wychwalaną przez krytykę wiedźmińską sagę!\r\n\r\nPóźniej mówiono, że człowiek ów nadszedł od północy, od Bramy Powroźniczej. Nie był stary, ale włosy miał zupełnie białe. Kiedy ściągnął płaszcz, okazało się, że na pasie za plecami ma miecz.\r\nBiałowłosego przywiodło do miasta królewskie orędzie: trzy tysiące orenów nagrody za odczarowanie nękającej mieszkańców Wyzimy strzygi.\r\n \r\nTakie czasy nastały. Dawniej po lasach jeno wilki wyły, teraz namnożyło się rozmaitego paskudztwa – gdzie spojrzysz, tam upiory, bazyliszki, diaboły, żywiołaki, wiły i utopce plugawe. A i niebacznie uwolniony z amfory dżinn, potrafiący zamienić życie spokojnego miasta w koszmar, się trafi.\r\n \r\nTu nie wystarczą zwykłe czary ani osinowe kołki. Tu trzeba zawodowca.\r\nWiedźmina. Mistrza magii i miecza. Tajemną sztuką wyuczonego, by strzec na świecie moralnej i biologicznej równowagi.'),
(2, 'Andrzej Sapkowski', 'Wiedźmin. Tom 2. Miecz przeznaczenia', '2010-11-10', '\"Miecz przeznaczenia\" jest zbiorem opowiadań stanowiących swoistą kontynuację przygód Geralta ze zbioru \"Ostatnie życzenie\", a zarazem poprzedza historię opisaną w tak zwanej sadze o Wiedźminie. Generalnie opowiadania składające się na omawiany zbiór nie różnią się niczym od napisanych wcześniej.\r\n\r\nGeralt dzięki swojej sile, odwadze i inteligencji walczy z potworami bądź w inny sposób stara się pomagać ludziom. Świat, w którym rozgrywa się akcja, jest przedstawiony w sposób niezwykle plastyczny, co sprawia, iż można go sobie bez większych problemów wyobrazić.\r\n\r\nKsiążka przesiąknięta jest emocjami, marzeniami i wartościami. Na kartach opowiadań widzimy miłość, poświęcenie, honor, determinację spowodowaną zamiarem udzielenia pomocy ukochanemu, przywiązanie do własnej ziemi.\r\n'),
(3, 'Andrzej Sapkowski', 'Wiedźmin. Tom 3. Krew elfów ', '2014-10-28', 'Tako rzecze Ithlinne, elfia wieszczka i uzdrowicielka: Drżyjcie, albowiem nadchodzi Niszczyciel Narodów. Stratują waszą ziemię i sznurem ją podzielą. Miasta wasze zostaną zburzone i pozbawione mieszkańców. Nietoperz i kruk w domach waszych zamieszkają, drzewo straci liść, zgnije owoc i zgorzknieje ziarno. Zaprawdę powiadam wam, oto nadchodzi czas miecza i topora, wiek wilczej zamieci. Miasto płonie, wąskie uliczki zieją ogniem i żarem. Narasta wrzask, odgłosy zajadłej walki, murem wstrząsają głuche uderzenia taranu. Krzyk, strach. Obezwładniający, paraliżujący, duszący strach.'),
(4, 'Andrzej Sapkowski', 'Wiedźmin. Tom 4. Czas pogardy ', '2010-11-10', 'Nastał czas pogardy, czas miecza i topora, czas wilczej zamieci. Wśród wojennej zawieruchy znaleźli się Geralt, Yennefer i Ciri, ale każde z nich gdzie indziej. Ciri czuje się porzucona, zapomniana, musi sama borykać się z trudami wędrówki przez obcy kraj, w którym się znalazła.\r\n\r\nCzy wiedźmin odnajdzie swoje przeznaczenie?\r\n'),
(5, 'Andrzej Sapkowski', 'Wiedźmin. Tom 5. Chrzest ognia ', '2010-11-10', 'Geralt, wyleczony przez driady z ran odniesionych w czasie nieudanego puczu na wyspie Thanedd, wyrusza na poszukiwanie przeznaczonego mu Dziecka Niespodzianki.\r\n\r\nOprócz nieodłącznego Jaskra, trubadura i domorosłego filozofa, do kompanii wiedźmina przystępują: pełna temperamentu łuczniczka Milva, nilfgaardzki rycerz - koszmar ze snów Ciri, którego poszukują najlepsi szpiedzy Cesarstwa, sprytny gnom zwiadowca, pięciu rubasznych krasnoludów oraz noszący się staroświecko i pachnący intensywnie ziołami cyrulik - osobnik jakby nie z tej bajki.\r\n'),
(6, 'Andrzej Sapkowski', 'Wiedźmin. Tom 6. Wieża jaskółki ', '2010-11-10', 'Ciri staje przed swoim przeznaczeniem.\r\nDrakkar wiozący Yennefer trafia w oko czarodziejskiego cyklonu.\r\nCzy wśród przyjaciół wiedźmina ukrywa się zdrajca?\r\n\r\nPrzedostatnia odsłona epopei o świecie wiedźmina i wojnach, jakie nim wstrząsają. W zagubionej wśród bagien chacie pustelnika ciężko ranna Ciri powraca do zdrowia. Jej tropem podążają bezlitośni zabójcy z Nilfgaardu.\r\n\r\nTymczasem drużyna Geralta, unikając coraz to nowych niebezpieczeństw, dociera wreszcie do ukrywających się druidów. Czy wiedźminowi uda się odnaleźć Ciri? Jaką rolę odegra osnuta legendą Wieża Jaskółki?\r\n'),
(7, 'Andrzej Sapkowski', 'Wiedźmin. Tom 7. Pani Jeziora ', '2010-11-10', '\"Potwór zaatakował z ciemności, z zasadzki, cicho i wrednie. Zmaterializował się nagle wśród mroku jak wybuchający płomień. Jak jęzor płomienia.\"\r\n\r\nSiódmy tom sagi o wiedźminie Geralcie, pięknej czarodziejce Yennefer i Cirilli - dziecku przeznaczenia.\r\n\r\nJaki los czeka wiedźmina? Czy dane mu będzie połączyć się z miłością jego życia? Czy ziści się złowieszcza przepowiednia i czy przetrwa świat ogarnięty morderczą wojną? Świat elfów, ludzi i krasnoludów.\r\n'),
(8, 'Andrzej Sapkowski', 'Wiedźmin. Tom 8. Sezon burz ', '2016-10-12', 'Oto nowy Sapkowski i nowy wiedźmin. Mistrz polskiej fantastyki znowu zaskakuje. \"Sezon burz\" nie opowiada bowiem o młodzieńczych latach białowłosego zabójcy potworów ani o jego losach po śmierci/nieśmierci kończącej ostatni tom sagi.\r\n\r\nNigdy nie mów nigdy! W powieści pojawiają się osoby doskonale czytelnikom znane, jak wierny druh Geralta – bard i poeta Jaskier – oraz jego ukochana, zwodnicza czarodziejka Yennefer, ale na scenę wkraczają też dosłownie i w przenośni postaci z zupełnie innych bajek. Ludzie, nieludzie i magiczną sztuką wyhodowane bestie. Opowieść zaczyna się wedle reguł gatunku: od trzęsienia ziemi, a potem napięcie rośnie. Wiedźmin stacza morderczą walkę z drapieżnikiem, który żyje tylko po to, żeby zabijać, wdaje się w bójkę z rosłymi, niezbyt sympatycznymi strażniczkami miejskimi, staje przed sądem, traci swe słynne miecze i przeżywa burzliwy romans z rudowłosą pięknością, zwaną Koral. A w tle toczą się królewskie i czarodziejskie intrygi. Pobrzmiewają pioruny i szaleją burze. I tak przez 404 strony porywającej lektury.\r\n\r\n\"Wiedźmin. Sezon Burz\" to w wiedźmińskiej historii rzecz osobna, nie prapoczątek i nie kontynuacja. Jak pisze autor: \"Opowieść trwa. Historia nie kończy się nigdy…\"\r\n\r\n\"Wielonożny stwór skakał i kręcił sie, kręcił niesmowicie szybko, wymachując łapami i szczękając starszliwymi żuwaczami. A wokół niego, jeszcze szybciej, tak szybko, że aż zamazywał się w oczach, tańczył człowiek. Uzbrojony w dwa miecze. W powietrze wyleciała najpierw jedna, potem druga, potem trzecia odrąbana łapa. Cięcia mieczy spadały na płaski korpus, z którego siknęły strugi zielonej mazi. Potwór szamotał się i ciskał, wreszcie dzikim skokiem rzucił się w las, do ucieczki. Nie uciekł daleko. Człowiek z mieczami dopadł go, przydeptał, z rozmachem przygwoździł do ziemi sztychami obu kling naraz...\".\r\nfragment książki\r\n');


ALTER TABLE `Books`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `Books`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
